### ISSUE TITLE
dataset load

### ISSUE THREAD

**Issue by automation-yy** [ajinkyanande/11785-project#1]
Hello, can you send me the dataset or the link to download the dataset?
train_loader_sonar,train_loader_camera,val_loader_sonar,val_loader_camera=load_data("sonar_camera_data/camera","sonar_camera_data/sonar")
Thank you very much.

**Comment by ajinkyanande** [comment]
Hey, sorry for the delay. Unfortunately, I'm not sure if I can share the dataset directly, as it was part of a collaboration with one of the labs.
